# Template for remapping license-plate datasets into Model B classes.
target_model: model_b_plate

source_to_target:
  license_plate: license_plate
  plate: license_plate
  number_plate: license_plate
  car_plate: license_plate
  vehicle_plate: license_plate
